import { expect, type Page, test } from "@playwright/test";

// Code export is a paid feature (closed-product pivot, 2026-07-22). An unentitled workspace gets
// the opening lines of the generated file plus an upgrade prompt, not the whole thing.
//
// The truncation itself is the API's decision (`deps.may_export_code`), and it's switched off
// without a `CALYPR_INTERNAL_KEY` — which is exactly the configuration this suite runs in, since
// every request here resolves to the shared `free` dev workspace and gating it would break the
// five specs that read the Code tab. So these tests stub the API response instead: what's under
// test is that the client renders a *server-truncated* payload correctly, which is the only part
// the browser is responsible for.

const PREVIEW = `"""Generated by Calypr."""

from typing import Annotated, TypedDict

from langchain_core.messages import AnyMessage
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages


class State(TypedDict):
    input: str
    messages: Annotated[list[AnyMessage], add_messages]
    output: str
`;

/** Serve a truncated /api/codegen response, as a `free` workspace would get in production. */
async function stubTruncatedCodegen(page: Page, totalLines = 96) {
  await page.route("**/api/codegen", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ code: PREVIEW, truncated: true, total_lines: totalLines }),
    });
  });
}

async function openCanvasWithAnAgent(page: Page) {
  await page.goto("/canvas");
  await page.getByTestId("dev-sign-in").click();
  await expect(page.locator(".react-flow__controls")).toBeVisible();
  await page.getByTestId("add-input").click();
  await page.getByTestId("add-agent").click();
  await page.getByTestId("add-output").click();
  await expect(page.getByTestId("node-agent")).toBeVisible();
  await page.getByTestId("toggle-code").click();
}

test("an unentitled workspace sees a readable preview, not a blank wall", async ({ page }) => {
  // The preview has to show real code: the pitch is that the generated Python is good, and a
  // fully obscured blob proves nothing worth paying for.
  await stubTruncatedCodegen(page);
  await openCanvasWithAnAgent(page);

  const code = page.getByTestId("code-output");
  await expect(code).toContainText("class State(TypedDict)");
  await expect(code).toContainText("from langgraph.graph import");
  // ...and it stops before the part being sold.
  await expect(code).not.toContainText("def build_graph");
});

test("the locked preview offers the upgrade and says how much is behind it", async ({ page }) => {
  await stubTruncatedCodegen(page, 96);
  await openCanvasWithAnAgent(page);

  const locked = page.getByTestId("code-locked");
  await expect(locked).toBeVisible();
  await expect(locked).toContainText("96 lines");
  await expect(page.getByTestId("code-upgrade")).toHaveAttribute("href", "/pricing");
});

test("copy and download are disabled while the file is withheld", async ({ page }) => {
  await stubTruncatedCodegen(page);
  await openCanvasWithAnAgent(page);

  await expect(page.getByTestId("code-locked")).toBeVisible();
  await expect(page.getByRole("button", { name: "Copy code" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Download code" })).toBeDisabled();
});

test("an entitled workspace gets the whole file and working actions", async ({ page }) => {
  // No stub: the API serves the full file here (no internal key ⇒ everyone is entitled), which
  // is also the control proving the tests above are driven by `truncated`, not by the fixture.
  await openCanvasWithAnAgent(page);

  await expect(page.getByTestId("code-output")).toContainText("def build_graph", {
    timeout: 15_000,
  });
  await expect(page.getByTestId("code-locked")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Copy code" })).toBeEnabled();
  await expect(page.getByRole("button", { name: "Download code" })).toBeEnabled();
});
