"use client";

import { AudioLines, Box, Download, ExternalLink, MoreHorizontal, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/components/ui/toast";
import { MediaViewer } from "@/components/MediaViewer";
import { type StoredAsset, deleteAsset, listAssets } from "@/lib/api";
import { downloadUrl, filenameFrom } from "@/lib/download";
import { relativeTime } from "@/lib/time";

import { DeleteConfirm } from "./DeleteConfirm";

const KINDS = [
  { id: "", label: "All" },
  { id: "image", label: "Images" },
  { id: "audio", label: "Audio" },
  { id: "3d", label: "3D" },
] as const;

function extFor(a: StoredAsset): string {
  // `model/gltf-binary` is the one content type whose subtype isn't the extension anyone wants —
  // a file called `model.gltf-binary` opens in nothing.
  if (a.kind === "3d") return "glb";
  const fromType = a.content_type?.split("/")[1];
  if (fromType) return fromType === "mpeg" ? "mp3" : fromType;
  return a.kind === "audio" ? "mp3" : "png";
}

/** Images and audio generated by this workspace's runs — the left rail's Media panel.
 *
 *  Workspace-scoped, not conversation-scoped, which is why it lives in the rail next to the
 *  other workspace tools rather than as a tab inside the Playground. Chat History is the
 *  opposite and stays with the chat.
 *
 *  Only *durably stored* media appears here. A deployment without blob storage configured still
 *  renders generated files in the chat (the node inlines them as a `data:` URI) but records
 *  nothing — so an empty panel there is correct, not broken, and the empty state says so. */
export function MediaTab({ refreshKey }: { refreshKey: number }) {
  const [query, setQuery] = useState("");
  const [debounced, setDebounced] = useState("");
  const [kind, setKind] = useState<string>("");
  const [items, setItems] = useState<StoredAsset[] | null>(null);
  const [deleting, setDeleting] = useState<StoredAsset | null>(null);
  const [busy, setBusy] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    const id = setTimeout(() => setDebounced(query.trim()), 250);
    return () => clearTimeout(id);
  }, [query]);

  // Promise chain, not an `async` body — see the note on `HistoryTab.load`.
  const load = useCallback(
    () =>
      listAssets({ q: debounced, kind: kind || undefined })
        .then((page) => setItems(page.items))
        .catch(() => setItems([])),
    [debounced, kind],
  );

  // `refreshKey` is bumped by every `asset` event the run stream delivers, so a file generated
  // while this tab was hidden is there when the user switches to it — without polling.
  useEffect(() => {
    load();
  }, [load, refreshKey]);

  async function confirmDelete() {
    if (!deleting) return;
    setBusy(true);
    const ok = await deleteAsset(deleting.id);
    setBusy(false);
    if (!ok) {
      toast("Could not delete that file.", "error");
      return;
    }
    setDeleting(null);
    void load();
  }

  return (
    <div className="flex h-full flex-col">
      {/* No header here — the left-panel shell in app/canvas/page.tsx renders one for every rail
          tab, at the h-11 that keeps it level with the Playground's header across the canvas. */}
      {/* The same `line` tab strip the Playground uses, so the two panels read as one system. */}
      <Tabs value={kind} onValueChange={(v) => setKind(v as string)}>
        <TabsList
          variant="line"
          // `h-12!` — the important modifier is load-bearing. `TabsList` sets `h-8` through a
          // `group-data-horizontal/tabs:` variant, which out-specifies a plain `h-12`, so the
          // strip stayed 32px and any padding just squeezed the labels tighter. At 32px the tabs
          // sat wedged between the panel header's border and their own.
          className="h-12! w-full justify-start border-b border-border px-2"
          data-testid="media-kinds"
        >
          {KINDS.map((k) => (
            <TabsTrigger
              key={k.id || "all"}
              value={k.id}
              data-testid={`media-kind-${k.label.toLowerCase()}`}
            >
              {k.label}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>
      <div className="border-b border-border p-3">
        <Input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search media…"
          data-testid="media-search"
        />
      </div>

      <div className="flex-1 space-y-3 overflow-auto p-3" data-testid="media-list">
        {items === null ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : items.length === 0 ? (
          <div className="rounded-lg border border-dashed border-border p-6 text-center">
            <p className="text-sm text-muted-foreground">
              {debounced || kind ? "No matching files." : "No generated media yet."}
            </p>
            {!debounced && !kind ? (
              <p className="mt-1 text-xs text-muted-foreground">
                Images and audio your runs generate are saved here.
              </p>
            ) : null}
          </div>
        ) : (
          // **One grid over `items`, not one per kind.** Images and audio used to render in two
          // stacked grids, so audio always began on a fresh row and the panel visibly broke in
          // half — even though both cells are the same size. Rendering the list in the order the
          // API returned it keeps newest-first meaningful across both kinds.
          <div className="grid grid-cols-2 gap-2">
            {items.map((a) => (
              <MediaCell key={a.id} asset={a} onDelete={() => setDeleting(a)} />
            ))}
          </div>
        )}
      </div>

      <DeleteConfirm
        open={deleting !== null}
        testId="media-delete-confirm"
        busy={busy}
        title="Delete file?"
        description={
          `“${deleting?.caption || "Untitled"}” will be permanently deleted. ` +
          "It will also disappear from the conversation that generated it. This can't be undone."
        }
        onConfirm={() => void confirmDelete()}
        onOpenChange={(o) => !o && setDeleting(null)}
      />
    </div>
  );
}

/**
 * One tile in the media grid — an image thumbnail or an audio card, in the same footprint so the
 * two kinds tile together instead of the grid breaking into sections.
 *
 * **Audio has no inline player.** A row of identical player pills told you nothing and ate the
 * space the caption needed; the caption — the opening of what was actually spoken — is the only
 * thing that tells two clips apart. Playing a clip is Open, one item down the menu, which hands
 * it to the browser's own player.
 */
function MediaCell({ asset, onDelete }: { asset: StoredAsset; onDelete: () => void }) {
  const [viewing, setViewing] = useState(false);
  const isImage = asset.kind === "image";
  const is3d = asset.kind === "3d";
  // Audio has no viewer — its player is the chat bubble, and "Open" in the menu hands the file to
  // the browser. Only the two visual kinds get a full-size window.
  const viewable = isImage || is3d;
  const caption =
    asset.caption || (isImage ? "Untitled" : is3d ? "Untitled model" : "Untitled audio");
  // Time and model moved off the face of the tile and into its tooltip: at this size they were a
  // third line of grey text competing with the one line that identifies the clip.
  const meta = [relativeTime(asset.created_at), asset.model].filter(Boolean).join(" · ");

  return (
    <figure
      data-testid="media-item"
      className="group relative overflow-hidden rounded-md border border-border"
    >
      {isImage ? (
        /* A plain <img>, not <ChatImage>: that component is built for a chat bubble (its own
           download affordance, intrinsic sizing) and fights a fixed-ratio grid cell. Not
           `next/image` either — these are arbitrary blob URLs, which the optimizer would need
           `remotePatterns` for, and `ChatImage` made the same call for the same reason. */
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={asset.url}
          alt={asset.caption}
          loading="lazy"
          onClick={() => setViewing(true)}
          className="aspect-square w-full cursor-zoom-in bg-muted object-cover"
          data-testid="media-thumb"
        />
      ) : (
        <div className="flex aspect-square w-full items-center justify-center bg-muted/40">
          {/* A glyph, not a render: a GLB has no thumbnail of its own, and spinning up WebGL for
              every cell in a grid to make one would cost far more than the tile is worth. */}
          {is3d ? (
            <button
              type="button"
              onClick={() => setViewing(true)}
              aria-label={`View ${asset.caption || "3D model"}`}
              data-testid="media-thumb"
              className="flex h-full w-full cursor-zoom-in items-center justify-center"
            >
              <Box className="h-7 w-7 text-muted-foreground" />
            </button>
          ) : (
            <AudioLines className="h-7 w-7 text-muted-foreground" />
          )}
        </div>
      )}

      <figcaption
        className="truncate px-2 py-1 text-xs text-muted-foreground"
        // The stored caption is capped, so hovering is the only way to see a long line in full.
        title={[caption, meta].filter(Boolean).join(" — ")}
        data-testid="media-caption"
      >
        {caption}
      </figcaption>

      <DropdownMenu>
        <DropdownMenuTrigger
          aria-label="File actions"
          data-testid="media-menu"
          className="absolute top-1 right-1 rounded-md bg-background/80 p-1 text-muted-foreground opacity-0 shadow-sm transition group-hover:opacity-100 hover:text-foreground data-[popup-open]:opacity-100"
        >
          <MoreHorizontal className="h-3.5 w-3.5" />
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-auto min-w-36">
          <DropdownMenuItem
            data-testid="media-download"
            onClick={() =>
              void downloadUrl(asset.url, filenameFrom(asset.caption, extFor(asset)))
            }
          >
            <Download className="h-3.5 w-3.5" /> Download
          </DropdownMenuItem>
          <DropdownMenuItem
            data-testid="media-open"
            onClick={() => window.open(asset.url, "_blank", "noopener")}
          >
            <ExternalLink className="h-3.5 w-3.5" /> Open
          </DropdownMenuItem>
          <DropdownMenuItem variant="destructive" data-testid="media-delete" onClick={onDelete}>
            <Trash2 className="h-3.5 w-3.5" /> Delete
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {viewable ? (
        <MediaViewer
          open={viewing}
          onOpenChange={setViewing}
          kind={isImage ? "image" : "3d"}
          src={asset.url}
          caption={caption}
        />
      ) : null}
    </figure>
  );
}

