"use client";

import { Download, ExternalLink, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { ChatAudio } from "@/components/ChatAudio";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/components/ui/toast";
import { type StoredAsset, deleteAsset, listAssets } from "@/lib/api";
import { downloadUrl, filenameFrom } from "@/lib/download";
import { relativeTime } from "@/lib/time";

import { DeleteConfirm } from "./DeleteConfirm";

const KINDS = [
  { id: "", label: "All" },
  { id: "image", label: "Images" },
  { id: "audio", label: "Audio" },
] as const;

function extFor(a: StoredAsset): string {
  const fromType = a.content_type?.split("/")[1];
  if (fromType) return fromType === "mpeg" ? "mp3" : fromType;
  return a.kind === "audio" ? "mp3" : "png";
}

/** Images and audio generated by this workspace's runs — the left rail's Media panel.
 *
 *  Workspace-scoped, not conversation-scoped, which is why it lives in the rail next to the
 *  other workspace tools rather than as a tab inside the Playground. Chat History is the
 *  opposite and stays with the chat.
 *
 *  Only *durably stored* media appears here. A deployment without blob storage configured still
 *  renders generated files in the chat (the node inlines them as a `data:` URI) but records
 *  nothing — so an empty panel there is correct, not broken, and the empty state says so. */
export function MediaTab({ refreshKey }: { refreshKey: number }) {
  const [query, setQuery] = useState("");
  const [debounced, setDebounced] = useState("");
  const [kind, setKind] = useState<string>("");
  const [items, setItems] = useState<StoredAsset[] | null>(null);
  const [deleting, setDeleting] = useState<StoredAsset | null>(null);
  const [busy, setBusy] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    const id = setTimeout(() => setDebounced(query.trim()), 250);
    return () => clearTimeout(id);
  }, [query]);

  // Promise chain, not an `async` body — see the note on `HistoryTab.load`.
  const load = useCallback(
    () =>
      listAssets({ q: debounced, kind: kind || undefined })
        .then((page) => setItems(page.items))
        .catch(() => setItems([])),
    [debounced, kind],
  );

  // `refreshKey` is bumped by every `asset` event the run stream delivers, so a file generated
  // while this tab was hidden is there when the user switches to it — without polling.
  useEffect(() => {
    load();
  }, [load, refreshKey]);

  async function confirmDelete() {
    if (!deleting) return;
    setBusy(true);
    const ok = await deleteAsset(deleting.id);
    setBusy(false);
    if (!ok) {
      toast("Could not delete that file.", "error");
      return;
    }
    setDeleting(null);
    void load();
  }

  const images = (items ?? []).filter((a) => a.kind === "image");
  const audio = (items ?? []).filter((a) => a.kind !== "image");

  return (
    <div className="flex h-full flex-col">
      {/* h-11 to match the Playground's header — the two panels sit side by side, so their
          headers and the tab strips beneath them have to share a baseline. */}
      <div className="flex h-11 shrink-0 items-center justify-between border-b border-border px-3">
        <span className="text-sm font-medium">Media</span>
      </div>
      {/* The same `line` tab strip the Playground uses, so the two panels read as one system. */}
      <Tabs value={kind} onValueChange={(v) => setKind(v as string)}>
        <TabsList
          variant="line"
          className="w-full justify-start border-b border-border px-2"
          data-testid="media-kinds"
        >
          {KINDS.map((k) => (
            <TabsTrigger
              key={k.id || "all"}
              value={k.id}
              data-testid={`media-kind-${k.label.toLowerCase()}`}
            >
              {k.label}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>
      <div className="border-b border-border p-3">
        <Input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search media…"
          data-testid="media-search"
        />
      </div>

      <div className="flex-1 space-y-3 overflow-auto p-3" data-testid="media-list">
        {items === null ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : items.length === 0 ? (
          <div className="rounded-lg border border-dashed border-border p-6 text-center">
            <p className="text-sm text-muted-foreground">
              {debounced || kind ? "No matching files." : "No generated media yet."}
            </p>
            {!debounced && !kind ? (
              <p className="mt-1 text-xs text-muted-foreground">
                Images and audio your runs generate are saved here.
              </p>
            ) : null}
          </div>
        ) : (
          <>
            {images.length > 0 ? (
              <div className="grid grid-cols-2 gap-2">
                {images.map((a) => (
                  <figure
                    key={a.id}
                    data-testid="media-item"
                    className="group relative overflow-hidden rounded-md border border-border"
                  >
                    {/* A plain <img>, not <ChatImage>: that component is built for a chat
                        bubble (its own download affordance, intrinsic sizing) and fights a
                        fixed-ratio grid cell. Not `next/image` either — these are arbitrary
                        blob URLs, which the optimizer would need `remotePatterns` for, and
                        `ChatImage` made the same call for the same reason. */}
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={a.url}
                      alt={a.caption}
                      loading="lazy"
                      className="aspect-square w-full bg-muted object-cover"
                    />
                    <figcaption className="truncate px-2 py-1 text-xs text-muted-foreground">
                      {a.caption || "Untitled"}
                    </figcaption>
                    <div className="absolute top-1 right-1 flex gap-1 opacity-0 transition group-hover:opacity-100">
                      <IconButton
                        label="Download"
                        testId="media-download"
                        onClick={() =>
                          void downloadUrl(a.url, filenameFrom(a.caption, extFor(a)))
                        }
                      >
                        <Download className="h-3.5 w-3.5" />
                      </IconButton>
                      <IconButton
                        label="Open in new tab"
                        testId="media-open"
                        onClick={() => window.open(a.url, "_blank", "noopener")}
                      >
                        <ExternalLink className="h-3.5 w-3.5" />
                      </IconButton>
                      <IconButton
                        label="Delete"
                        testId="media-delete"
                        onClick={() => setDeleting(a)}
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </IconButton>
                    </div>
                  </figure>
                ))}
              </div>
            ) : null}

            {/* Audio leads with text, images don't. A thumbnail identifies itself at a glance;
                a row of identical player pills does not, and once a few pile up there is nothing
                to tell them apart. The caption is the opening of what was actually spoken, which
                is the cheapest true description available without transcribing anything. */}
            {audio.map((a) => (
              <div
                key={a.id}
                data-testid="media-item"
                className="group rounded-md border border-border p-2"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0">
                    <p
                      className="truncate text-sm"
                      // The stored caption is capped, so hovering is the only way to see a
                      // long line in full.
                      title={a.caption || undefined}
                      data-testid="media-caption"
                    >
                      {a.caption || "Untitled audio"}
                    </p>
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      {[relativeTime(a.created_at), a.model].filter(Boolean).join(" · ")}
                    </p>
                  </div>
                  <div className="shrink-0 opacity-0 transition group-hover:opacity-100">
                    <IconButton
                      label="Delete"
                      testId="media-delete"
                      onClick={() => setDeleting(a)}
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </IconButton>
                  </div>
                </div>
                {/* The compact player, reused as-is — it already carries its own download
                    control and looks identical to the one in the transcript. */}
                <div className="mt-1.5">
                  <ChatAudio src={a.url} label={a.caption || "audio"} />
                </div>
              </div>
            ))}
          </>
        )}
      </div>

      <DeleteConfirm
        open={deleting !== null}
        testId="media-delete-confirm"
        busy={busy}
        title="Delete file?"
        description={
          `“${deleting?.caption || "Untitled"}” will be permanently deleted. ` +
          "It will also disappear from the conversation that generated it. This can't be undone."
        }
        onConfirm={() => void confirmDelete()}
        onOpenChange={(o) => !o && setDeleting(null)}
      />
    </div>
  );
}

function IconButton({
  label,
  testId,
  onClick,
  children,
}: {
  label: string;
  testId: string;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      data-testid={testId}
      onClick={onClick}
      className="rounded bg-background/90 p-1 text-muted-foreground shadow-sm hover:text-foreground"
    >
      {children}
    </button>
  );
}
