import {
  ArrowRight,
  Boxes,
  Code2,
  GitBranch,
  Play,
  ShieldCheck,
  Sparkles,
  Workflow,
} from "lucide-react";
import Link from "next/link";

import { HeroDither } from "@/components/landing/HeroDither";
import { HeroTrails } from "@/components/landing/HeroTrails";
import { SiteFooter } from "@/components/site/Footer";
import { SiteHeader } from "@/components/site/Header";
import { buttonVariants } from "@/components/ui/button";

// ── small building blocks ───────────────────────────────────────────────────

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center gap-2 rounded-full border border-border bg-card/40 px-3 py-1 font-mono text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
      {children}
    </span>
  );
}

// A monochrome echo of the real canvas: dotted grid + connected nodes.
// ── content ───────────────────────────────────────────────────────────────

const PILLARS = [
  {
    icon: ShieldCheck,
    title: "No ceiling",
    body: "Every graph compiles to standalone Python (LangGraph) you own. Hit a limit? Drop into a Custom Code node — it round-trips verbatim.",
  },
  {
    icon: Boxes,
    title: "Composable nodes",
    body: "Input, Agent, Tools, Router, Evaluator, Memory, Responder/Revisor. Wire them into anything from a simple reflex to full Reflexion.",
  },
  {
    icon: Play,
    title: "Run it live",
    body: "Stream your agent in the playground. The built-in fake model needs no API key — bring OpenAI or Anthropic when you're ready.",
  },
];

const STEPS = [
  {
    n: "01",
    title: "Draw the graph",
    body: "Start from a template, or drop nodes and connect them. The canvas is just state — nodes and edges.",
  },
  {
    n: "02",
    title: "Run & inspect",
    body: "Chat with it in the playground. Watch tokens stream and tool calls fire, turn by turn.",
  },
  {
    n: "03",
    title: "Own the code",
    body: "Open the Code view and copy idiomatic LangGraph. Zero Calypr dependency, zero lock-in.",
  },
];

const TEMPLATES = [
  ["Simple reflex", "Reacts to the latest input."],
  ["Model-based", "Remembers the conversation."],
  ["Goal-based", "Plans toward a goal."],
  ["Utility-based", "Generates N, keeps the best."],
  ["Reflection", "Critiques and revises itself."],
  ["Learning", "Adapts from feedback."],
  ["ReAct", "Reasons and calls tools in a loop."],
  ["Reflexion", "Researches, then self-revises."],
];

const CODE = `"""ReAct Agent — generated by Calypr. Owns no Calypr dependency."""

def node_agent(state: State) -> dict:
    """Model-based agent: respond using the full conversation state."""
    model = init_chat_model("gpt-4o-mini", temperature=0.7).bind_tools([web_search])
    messages = state.get("messages") or []
    reply = model.invoke([SystemMessage(content=system), *messages])
    return {"messages": [reply]}


def build_graph():
    graph = StateGraph(State)
    graph.add_node("agent", node_agent)
    graph.add_node("tools", ToolNode([web_search]))
    graph.add_conditional_edges("agent", tools_condition, {"tools": "tools", END: "out"})
    graph.add_edge("tools", "agent")
    return graph.compile()`;

// ── page ────────────────────────────────────────────────────────────────────

export default function Home() {
  const primaryBtn = buttonVariants({ size: "lg" });
  const ghostBtn = buttonVariants({ size: "lg", variant: "outline" });

  return (
    <div className="relative flex min-h-full flex-col">
      {/* atmospheric grayscale glow */}
      <div
        aria-hidden
        className="pointer-events-none fixed inset-0 -z-10 bg-[radial-gradient(60%_50%_at_50%_-10%,rgba(255,255,255,0.06),transparent)]"
      />

      {/* nav */}
      <SiteHeader />

      {/* hero */}
      <section className="relative">
        {/* dithered-sphere shader backdrop + nebula + spark trails, framed away from the text by
            a radial mask so the headline stays crisp */}
        <div
          aria-hidden
          className="pointer-events-none absolute inset-0 overflow-hidden [mask-image:radial-gradient(105%_75%_at_50%_42%,transparent_16%,black_58%)]"
        >
          {/* nebula colour blooms, behind the globe */}
          <div className="nebula absolute left-1/2 top-[42%] h-[70vh] w-[70vh] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[radial-gradient(circle,rgba(0,178,255,0.22),transparent_62%)]" />
          <div className="nebula nebula-2 absolute left-[38%] top-[38%] h-[55vh] w-[55vh] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[radial-gradient(circle,rgba(129,90,255,0.16),transparent_60%)]" />
          <HeroDither />
          <HeroTrails />
        </div>
        <div className="relative mx-auto flex min-h-[82vh] w-full max-w-6xl flex-col justify-center px-5 pt-24 pb-20 sm:pt-32">
        <div className="flex flex-col items-center text-center">
          <div className="animate-in fade-in slide-in-from-bottom-3 duration-700">
            <Eyebrow>
              <Sparkles className="h-3 w-3" /> prompt → canvas → code
            </Eyebrow>
          </div>
          <h1 className="animate-in fade-in slide-in-from-bottom-4 mt-7 max-w-4xl text-balance text-5xl font-semibold leading-[1.02] tracking-tight duration-700 sm:text-7xl lg:text-8xl">
            Design AI agents visually.
            <br />
            <span className="text-muted-foreground">Leave with the code.</span>
          </h1>
          <div className="animate-in fade-in slide-in-from-bottom-4 mt-9 flex flex-wrap items-center justify-center gap-3 delay-100 duration-700">
            <Link href="/canvas" className={primaryBtn}>
              Open the canvas <ArrowRight className="h-4 w-4" />
            </Link>
            <a href="#code" className={ghostBtn}>
              See the generated code
            </a>
          </div>
        </div>
        </div>
      </section>

      {/* pillars */}
      <section className="mx-auto w-full max-w-6xl px-5 py-16">
        <div className="grid gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-3">
          {PILLARS.map(({ icon: Icon, title, body }) => (
            <div key={title} className="bg-background p-7">
              <Icon className="h-5 w-5 text-foreground" />
              <h3 className="mt-4 text-base font-medium tracking-tight">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* how it works */}
      <section id="how" className="mx-auto w-full max-w-6xl px-5 py-16">
        <div className="max-w-2xl">
          <Eyebrow>
            <Workflow className="h-3 w-3" /> how it works
          </Eyebrow>
          <h2 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">
            From idea to ownable agent, in three moves.
          </h2>
        </div>
        <div className="mt-10 grid gap-8 sm:grid-cols-3">
          {STEPS.map(({ n, title, body }) => (
            <div key={n} className="border-t border-border pt-5">
              <span className="font-mono text-sm text-muted-foreground">{n}</span>
              <h3 className="mt-3 text-lg font-medium tracking-tight">{title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* templates */}
      <section id="templates" className="mx-auto w-full max-w-6xl px-5 py-16">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div className="max-w-2xl">
            <Eyebrow>
              <GitBranch className="h-3 w-3" /> start from a template
            </Eyebrow>
            <h2 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">
              The agent ladder, ready to run.
            </h2>
            <p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">
              Eight archetypes from a single reflex up to tool-using ReAct and self-revising
              Reflexion. Load one, run it, read its code.
            </p>
          </div>
        </div>
        <div className="mt-10 grid gap-px overflow-hidden rounded-xl border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">
          {TEMPLATES.map(([name, desc]) => (
            <div key={name} className="group bg-background p-6 transition-colors hover:bg-card/60">
              <div className="flex items-center justify-between">
                <span className="font-mono text-xs text-muted-foreground">tpl</span>
                <span className="h-1.5 w-1.5 rounded-full bg-foreground opacity-40 transition-opacity group-hover:opacity-100" />
              </div>
              <h3 className="mt-6 text-base font-medium tracking-tight">{name}</h3>
              <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* code showcase */}
      <section id="code" className="mx-auto w-full max-w-6xl px-5 py-16">
        <div className="grid items-center gap-10 lg:grid-cols-2">
          <div>
            <Eyebrow>
              <Code2 className="h-3 w-3" /> the canvas is the code
            </Eyebrow>
            <h2 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">
              Export Python you&rsquo;d actually merge.
            </h2>
            <p className="mt-4 max-w-md text-sm leading-relaxed text-muted-foreground">
              Every node carries its own code generator, so the graph you draw projects to
              idiomatic LangGraph — grouped imports, a typed <code className="font-mono text-foreground">State</code>,
              one function per node, the canonical tool loop. A round-trip test proves the
              generated module runs identically to the canvas.
            </p>
            <Link href="/canvas" className={`${buttonVariants({ variant: "outline" })} mt-7`}>
              Open the Code view <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
          <div className="overflow-hidden rounded-xl border border-border bg-card/40">
            <div className="flex items-center gap-1.5 border-b border-border px-4 py-2.5">
              <span className="h-2.5 w-2.5 rounded-full border border-border" />
              <span className="h-2.5 w-2.5 rounded-full border border-border" />
              <span className="h-2.5 w-2.5 rounded-full border border-border" />
              <span className="ml-3 font-mono text-[11px] text-muted-foreground">agent.py</span>
            </div>
            <pre className="overflow-x-auto p-5 font-mono text-[12px] leading-relaxed text-muted-foreground">
              <code>{CODE}</code>
            </pre>
          </div>
        </div>
      </section>

      {/* cta */}
      <section className="mx-auto w-full max-w-6xl px-5 py-20">
        <div className="dotted relative overflow-hidden rounded-2xl border border-border bg-card/30 px-8 py-16 text-center">
          <h2 className="mx-auto max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">
            From a prompt to an agent you own.
          </h2>
          <p className="mx-auto mt-4 max-w-md text-sm leading-relaxed text-muted-foreground">
            No black box. No lock-in. Draw it, run it, take the code with you.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
            <Link href="/canvas" className={primaryBtn}>
              Open the canvas <ArrowRight className="h-4 w-4" />
            </Link>
            <Link href="/sign-in" className={ghostBtn}>
              Sign in
            </Link>
          </div>
        </div>
      </section>

      {/* footer */}
      <SiteFooter />
    </div>
  );
}
